### PR TITLE
rotate travis-ci key per SEC-267

### PR DESCRIPTION
**Pull request by josh-janrain**

### CODE REVIEW

**Comment by josh-janrain** [comment]
@cameron-white-janrain does this change look ok to you?

**Comment by josh-janrain** [comment]
@cameron-white-janrain  this project doesn't appear to be setup in the janrain travis-ci account? Was going to just move these vars over to travis-ci settings.

**Comment by cameron-white-janrain** [comment]
Looks good!

**Comment by cameron-white-janrain** [comment]
What do you mean Travis-CI account. It's a public repo so it should be in Travis-ci.org not Travis-ci.com

**Pull request merged**
